//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoDiabetC3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExpedientePaciente
    {
        public int IDExpediente { get; set; }
        public string CorreoPaciente { get; set; }
        public string NombrePac { get; set; }
        public string ApellidoPatPac { get; set; }
        public string ApellidoMatPac { get; set; }
        public string Sexo { get; set; }
        public Nullable<int> Edad { get; set; }
        public string Enfermedad { get; set; }
        public Nullable<double> Peso { get; set; }
        public string TipoDeSangre { get; set; }
        public string TratamientosActuales { get; set; }
        public string TratamientosAnteriores { get; set; }
        public string CorreoDoc { get; set; }
    
        public virtual RegistroDoctor RegistroDoctor { get; set; }
        public virtual RegistroPaciente RegistroPaciente { get; set; }
    }
}
