//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoDiabetC3.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ProgramaHelperEntities : DbContext
    {
        public ProgramaHelperEntities()
            : base("name=ProgramaHelperEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CitasAgendadas> CitasAgendadas { get; set; }
        public virtual DbSet<ExpedientePaciente> ExpedientePaciente { get; set; }
        public virtual DbSet<Niveles> Niveles { get; set; }
        public virtual DbSet<Recetas> Recetas { get; set; }
        public virtual DbSet<RegistroDoctor> RegistroDoctor { get; set; }
        public virtual DbSet<RegistroPaciente> RegistroPaciente { get; set; }
    }
}
