//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoDiabetC3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Niveles
    {
        public int IDNiveles { get; set; }
        public string CorreoPaciente { get; set; }
        public string NombrePac { get; set; }
        public string ApellidoPatPac { get; set; }
        public string ApellidoMatPac { get; set; }
        public string Enfermedad { get; set; }
        public Nullable<double> Niveles_glucosa { get; set; }
        public Nullable<double> Niveles_presion { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public string CorreoDoc { get; set; }
    
        public virtual RegistroDoctor RegistroDoctor { get; set; }
        public virtual RegistroPaciente RegistroPaciente { get; set; }
    }
}
