//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoDiabetC3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RegistroDoctor
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RegistroDoctor()
        {
            this.CitasAgendadas = new HashSet<CitasAgendadas>();
            this.ExpedientePaciente = new HashSet<ExpedientePaciente>();
            this.Niveles = new HashSet<Niveles>();
            this.Recetas = new HashSet<Recetas>();
        }
    
        public string NombreDoc { get; set; }
        public string ApellidoPatDoc { get; set; }
        public string ApellidoMatDoc { get; set; }
        public string CorreoDoc { get; set; }
        public string Contraseña { get; set; }
        public string CedulaProfesional { get; set; }
        public string FormaciónAcademica { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CitasAgendadas> CitasAgendadas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ExpedientePaciente> ExpedientePaciente { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Niveles> Niveles { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Recetas> Recetas { get; set; }
    }
}
